### PR TITLE
mv index.html to /usr/lib/ttyd/index.html

### PR DESCRIPTION
**Pull request by huoyinghao**
https://github.com/cloudtty/cloudtty/issues/131

### CODE REVIEW

**Comment by calvin0327** [comment]
https://github.com/cloudtty/cloudtty/blob/main/pkg/manifests/manifests.go#L46

This position need be update synchronously.

**Comment by calvin0327** [comment]
@huoyinghao thanks your contribution

**Comment by huoyinghao** [comment]
https://github.com/cloudtty/cloudtty/issues/131

**Comment by calvin0327** [comment]
LGTM

**Comment by calvin0327** [comment]
thanks. @huoyinghao

**Pull request merged**
