### PR TITLE
upgrade cmd to cobra

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin <wen.chen@daocloud.io>

/kind feature

upgrade our cmd to cobra.
* add `--verion` `--kubeconfig` and more `ElectionLease` options.
* replace log to `klog`

### CODE REVIEW

**Comment by panpan0000** [comment]
Why do we need `ElectionLease ` ?

**Comment by calvin0327** [comment]
> Why do we need `ElectionLease` ?

If we are prepare to add mutils operator replicas to ensure high availability, wo need support elections feature. 
We used to support it, just not very elegant.

**Comment by panpan0000** [comment]
are those all necessary for cobra?
image

**Comment by calvin0327** [comment]
> are those all necessary for cobra? image

we did not have a vendor directory before, the following features of cloudtty are more and more, and it is necessary to add the vendor directory.

**Comment by calvin0327** [comment]
@panpan0000  We did not have a vendor directory before, but cloudtty has more and more features, so it is necessary to add a vendor directory

**Pull request merged**
