### PR TITLE
update the api group

### PR DESCRIPTION
**Pull request by calvin0327**
fixed: https://github.com/cloudtty/cloudtty/issues/6

/kind feature

update the api group.

### CODE REVIEW

**Comment by panpan0000** [comment]
lgtm. a minor comments: should we check-in those auto-generated files by kube-builder ? like subfolders under `config`?

**Comment by calvin0327** [comment]
> lgtm. a minor comments: should we check-in those auto-generated files by kube-builder ? like subfolders under `config`?

I think those are necessary,  although these config is generated by using kube-builder,  users still need them to install the service manually. Unless we provide a makefile that generates these files.

**Review by panpan0000 — APPROVED** [review]
lgtm now.

**Pull request merged**
